"""add saved destinations

Revision ID: 0a298982252e
Revises: 002_add_user_profile_fields
Create Date: 2026-08-22 14:37:12.089553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a298982252e'
down_revision: Union[str, None] = '002_add_user_profile_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_destinations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'city_id', name='uq_user_city')
    )
    op.create_index(op.f('ix_saved_destinations_city_id'), 'saved_destinations', ['city_id'], unique=False)
    op.create_index(op.f('ix_saved_destinations_user_id'), 'saved_destinations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_destinations_user_id'), table_name='saved_destinations')
    op.drop_index(op.f('ix_saved_destinations_city_id'), table_name='saved_destinations')
    op.drop_table('saved_destinations')
    # ### end Alembic commands ###
